# **Assignment 1(Python Basic, NumPy Basic)**

Deadline: 24th September 2020

Submission: Please submit a pdf file, which includes:


1.   Colab Link(source code with comment)
2.   Screenshots of the output of your program (please provide 3 test cases for question1 & 2)



# **Question 1**

You are given a string s and an integer array indices with same length.

The string s will be shuffled such that the character at the i-th position will move to "address of element i in indices" of the shuffled string.

**Example 1:**
Input: s = "pet", indices = [0,1,2]

Output: "pet"

Explanation: After shuffling, each character remains in its position.

**Example 2:**
Input: s = "comp", indices = [3,0,1,2]

Output: "pcom"

**Example 3:**
Input: s = "wesleyyam", indices = [1,3,5,7,8,6,4,2,0]

Output: "elyamyesw"

**Contstraints**

s.length == indices.length

1 <= n <= 15

s contains only lower-case English letters.

All values of indices are unique (i.e. indices is a permutation of the integers from 0 to n - 1).

# **Question 2**
You are given the target number n. Each time you can only add 1 or add 2. You need to find how many ways to calculate the target.

**Input** : the target ; 
**Output** : the number of the ways.

**Example 1:**

Input: 2

Output: 2

Explanation: There are 2 ways to calculate the target number 2.
1. 1  + 1 
2. 2 

**Example 2:**

Input: 3

Output: 3

Explanation: There are 3 ways to calculate the target number 3.
1. 1  + 1  + 1 
2. 1  + 2 
3. 2  + 1 
 
**Constraints**

1 <= n <= 50



# **Question 3**

**3.1 Create a 4X2 integer array with random value and Prints the following attributes. Then reshape it to a 2X4 NumPy array**


*   The shape of an array
*   Array dimensions
*   The Length of each element of the array in bytes

Example expected output:

```
[[222 111]
 [502     0]
 [3333   -111]
 [    0     0]]

1. Array Shape:  (4, 2)
2. Array dimensions are  2
3. Length of each element of array in bytes is  8

[[222 502 3333 0]
[111 0 -111 0]]
```
**3.2 Replace column two of a 3x3 NumPy Array with numpy.array([[10,10,10]]).**

Example:
```
Original array:
[[34 43 73]
 [82 22 12]
 [53 94 66]]

New Column:
[[10]
 [10]
 [10]]

Result array:
[[34 10 73]
 [82 10 12]
 [53 10 66]]
```

**3.3 Try to expand the dimension of a NumPy Array.**

Expand a 3x3 matrix to 3x3x1x1 matrix







# **Congratulation! You have completed the assignment.**